# Generated by Django 5.1 on 2024-09-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_infouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='infouser',
            name='cedula',
            field=models.SmallIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='telefono',
            field=models.SmallIntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.sexo'),
        ),
    ]
