# Generated by Django 5.1 on 2024-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_sexo_alter_infouser_cedula_alter_infouser_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='cedula',
            field=models.SmallIntegerField(max_length=10),
        ),
    ]
